name: Check Version and Create Tag

on:
  push:
    branches:
      - master

jobs:
  version_check:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check_version.outputs.version_changed }}
      new_version: ${{ steps.check_version.outputs.new_version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check version changes
        id: check_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2)
          echo "Current version: $VERSION"
          git fetch --prune --unshallow --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
          if [ "v$VERSION" != "$LATEST_TAG" ]; then
            echo "version_changed=true" >> "$GITHUB_OUTPUT"
            echo "new_version=v$VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "version_changed=false" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

  push_tags:
    needs: version_check
    runs-on: ubuntu-latest
    if: needs.version_check.outputs.version_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        name: Push tags
        id: push_new_tag
        with:
          tag: ${{ needs.version_check.outputs.new_version }}
          tag_exists_error: false
          message: "Flutter Qui Release :: ${{ needs.version_check.outputs.new_version }}"

      - run: |
          echo "Tag pushed: ${{ steps.push_new_tag.outputs.TAG_EXISTS }}"
